server:
  port: 8080

web:
  upload-path: D:/upload/
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://localhost:3306/ams?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置
    #配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
  profiles:
    active: prd
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  messages:
      # 国际化资源文件路径
      basename: i18n/messages
      encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      # 主键生成策略: UUID
      id-type: 4
    configuration:
      call-setters-on-nulls: true


#默认密码
password: 123456